Connection status handling
brimsec/brim pull request #1150
Opened 2020-10-15 16:10 UTC by mason-fish

fixes #1099 

**Changes**
 * Introduce connection statuses, stored in the clusters state.
 * Persist spaces state.
 * Initialization no longer depends on zqd and instead the data syncs come from the loaded app components

Every time the app loads we reset all statuses to "initial", indicating that we are unsure if the connection will succeed yet, and also indicating that we need to sync with server data. While syncing, if the connection fails we set the status to "disconnected" and display as much in a new tab content page where the user my attempt to retry.

![brim](https://user-images.githubusercontent.com/14865533/96154598-d632d800-0ec3-11eb-9499-4b3203f0ab32.gif)

Signed-off-by: Mason Fish <mason@looky.cloud>

2020-10-15 19:03 UTC, jameskerr requested changes
Right on! I like the code. I'm glad we talked and thought about it for a minute. Thanks for deleting all that old login stuff too.

In addition to the suggestions below, here are a few thoughts.

**Yellow Notice**

Now that we have this connection error view, the yellow notice that says "Failed to fetch" is unnecessary. I think it should not appear in this case (when we're testing out a connection). 

<img width="300" alt="Screen Shot 2020-10-15 at 10 41 01 AM" src="https://user-images.githubusercontent.com/3460638/96172280-08036900-0edb-11eb-97cd-c65e92acae37.png">

This might be more difficult than it seems. We pop up that "Notice" if any request in the whole app throws. You'll have to see if there is a way to remove the error handler only here, or if we need to remove it from where it is now and place it only where it's needed.

**Wording of notice**


As Al suggested, I think the wording of this error message needs to be updated to:

```
The service at {host}:{port} could not be reached.
```

<img width="472" alt="Screen Shot 2020-10-15 at 10 40 52 AM" src="https://user-images.githubusercontent.com/3460638/96172772-c0311180-0edb-11eb-9f05-70baa2b3dcff.png">

2020-10-15 20:51 UTC, mason-fish commented on src/js/components/ConnectionError.tsx
> +    await retry()
ah interesting! I had put in a wait just to test that it worked properly but then took it back out. I noticed the missing feedback then and that's why I added the Notice to the retry method, but if we end up removing that then I def agree that some sort of feedback is important

2020-10-15 20:51 UTC, mason-fish commented on src/js/components/ConnectionError.tsx
> +const StyledHeader = styled.h1`
sure thing

2020-10-20 19:45 UTC, jameskerr approved these changes
Looks awesome. I like the delay, works very well.

2020-10-20 19:45 UTC, jameskerr commented on src/js/components/ClusterPicker.tsx
> +          dispatch(Current.setConnectionId(c.id))
Oh nice! Easy

2020-10-21 17:43 UTC, merged