add debug logs in linux autoupdate
brimsec/brim pull request #1244
Opened 2020-11-27 03:31 UTC by mason-fish

Signed-off-by: Mason Fish <mason@looky.cloud>

2020-11-30 18:20 UTC, mason-fish commented on package.json
> -  "version": "0.19.0",
I'm using CI to build the releases for me just so I can test this out. Once done I'll switch this back to 19.

2020-12-07 16:59 UTC, jameskerr reviewed
This was not part of your diff, but while reviewing the file I noticed that the line comment and the line below it are not in accord:

https://github.com/brimsec/brim/blob/54484d05718c041a1603519346977341c812fd2f/src/js/electron/autoUpdater.ts#L72-L73

2020-12-07 17:27 UTC, jameskerr requested changes
It seems the code below does the trick at fixing the ticket, so I won't hold it back. But I do notice some duplication in checking the version and returning early. Also some duplication in the timeout checks. 

This code seems so important for users, it makes me nervous that we don't have tests around it. Because this is the intersection of so many systems, it would actually be hard to test. We'd have to mock the api server, the electron app api, the electron dialog api, and the autoupdater api.

Not in this PR, but next time we need to touch this code, I think we should invest in some tests like that.

My only requested change would be to remove that await from the main.ts function.

2020-12-07 17:27 UTC, jameskerr commented on src/js/electron/main.ts
> +      await setupAutoUpdater()
Is the await is necessary. I don't think we want to hold up this main function to wait for the autoUpdater code to resolve. The `.catch()` syntax will let the main function continue running.

2020-12-15 19:12 UTC, jameskerr approved these changes
Thanks for the changes!

2020-12-15 19:12 UTC, jameskerr commented on src/js/electron/autoUpdater.ts
> +  setInterval(updateCb, 24 * 60 * 60 * 1000)
Nice!

2020-12-15 21:04 UTC, merged