Export ndjson csv
brimsec/brim pull request #1302
Opened 2020-12-23 18:37 UTC by mason-fish

fixes #1090 

Adds an export modal with, for now, a simple format choice to be made before we send the user along to the existing save-file-to flow. This enables them to specify the csv and ndjson formats which zqd now offers.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/14865533/103027097-1341c900-450a-11eb-88b0-0c778031191d.png">

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/14865533/103027263-5ac85500-450a-11eb-8f14-0161ee4580cf.png">
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/14865533/103027360-89463000-450a-11eb-918f-d32bbb96b151.png">

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/14865533/103027195-3e2c1d00-450a-11eb-80f0-02f4c62cc035.png">

<img width="343" alt="image" src="https://user-images.githubusercontent.com/14865533/103027213-44ba9480-450a-11eb-920e-b70f21cfaba2.png">

2020-12-23 19:52 UTC, philrz commented
@mason-fish: It's cool that you put the functionality in here to "gray out" CSV export if the records are non-uniform. But if you're hitting a `zqd` endpoint to get the data for export, @nwt's pending work on https://github.com/brimsec/zq/issues/1271 should render that unnecessary, as I understand it.

2020-12-23 20:50 UTC, jameskerr requested changes
Nice Mason! Looks great. I have a few stylistic edits for you:

1. Make each radio label a click target for the label. Sometimes this is done by wrapping the <input> element with the <label> element. Other times you can use <label for={name}/> I think...
2. Make the cursor for each label `cursor: default`. I think this looks more app like.
3. Make sure the label is grayed out as well as the radio if it's disabled. `var(--slate)` is a good grayed out color.
4. If CSV is disabled, place the help text right under the label instead of in a tooltip. I think it's important enough to not hide behind hover. There is plenty of available space as well. Although it looks like that code path might be going away due to Noah's work in zqd.

I think these visual changes look good. Let me know if you feel strongly oppose any of them. 

<img width="389" alt="Screen Shot 2020-12-23 at 12 55 20 PM" src="https://user-images.githubusercontent.com/3460638/103036228-2068b300-451e-11eb-8709-92e07b250582.png">

1. Make the title "Export Results"
2. Left align the form
3. Indent the radio buttons by 12px
4. Lowercase the options
5. Remove the footer background color (I think it only needs to be a darker color if there is some scrollable content above it.

2020-12-23 20:50 UTC, jameskerr commented on src/js/components/ExportModal.tsx
> +            icon={isExporting ? <MacSpinner light /> : null}
It think we should allow the user to continue to use the app while the data is being exported. If I'm reading this right, this waits until the export is finished before dismissing?

2020-12-23 20:50 UTC, jameskerr commented on src/js/components/ExportModal.tsx
> +            icon={isExporting ? <MacSpinner light /> : null}
I do appreciate the desire to be consistent with the popNotices. I think we need a universal place to show "downloading" statuses. Right now we have:

1. Space import progress
2. Pcap download progress
3. Export file progress

They each have their own progress indicators. I'll think of a design for this.

2020-12-29 20:10 UTC, jameskerr commented
Hey Mason, here is another round of feedback. I thought the red text was too jarring for the warning, so I  brainstormed in sketch and ended up with a design for the modal that I think looks good. The link is at the bottom with the dimensions and spacing of everything.

1. Export complete pops up before it actually completes, looks the promise needs to be returned in `exportResults.ts`. 
2. There is no indication progress indicator in this version. I'd suggest putting the old one (the notice that looks like a pop notice but is different) back in for now until we have a solid replacement.
3. I think it would be good to use the default radio buttons for the OS that brim is being run on. They look great and feel "native". This can be done by simply following the semantic markup for radio buttons as shown here. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio. This will also allow the user to click on the text of the radio button to select it, rather than having to click on the small dot.
4. Here is a link to a design for the spacing and position of the items. https://www.sketch.com/s/4b2957a2-910e-403c-9fda-617de055c061/a/zx7EjKy#Inspector The disabled state should have the `cursor: disabled` style as well.

If you need more clarification on any of the items above, let me know.

2021-01-04 23:16 UTC, jameskerr approved these changes
This is great stuff Mason. Thanks for your patience during our back and forth discussions. I think the react toast library has a nice api and look forward to using it other places. In another ticket, I'll take a look at how I can theme it to be more consistent with the Brim App.

2021-01-04 23:48 UTC, merged